name: readme-sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: update date
        run: |
          # This looks for the hidden comment and updates the date inside it
          sed -i "s/<!-- Last updated: .* -->/<!-- Last updated: $(date -u +'%b %d, %Y') -->/g" README.md

      - name: git push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: refresh timestamp"
          git push
