name: readme-sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: update date
        run: |
          sed -i "s/Last updated: .*/Last updated: $(date -u +'%b %d, %Y')/g" README.md

      - name: git push
        run: |
          git config user.name "YourName"
          git config user.email "your-email@example.com"
          git add README.md
          git commit -m "docs: refresh timestamp"
          git push
